### ISSUE TITLE
TimeoutExpired exception not found

### ISSUE THREAD

**Issue by Vanderhoof** [hao-lee/Graphvizer#10]
Hi!
Plugin often crashes lately with the following output in the console:

```python
indexing [job 63]: no files were indexed out of the 54 queued, abandoning crawl
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/***/Library/Application Support/Sublime Text 3/Packages/Graphvizer/graphvizer.py", line 72, in dot_thread
    stdout, stderr = process.communicate(timeout=self.dot_timeout)
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1556, in _communicate
  File "./python3.3/subprocess.py", line 1644, in _communicate_with_poll
  File "./python3.3/subprocess.py", line 946, in _check_timeout
subprocess.TimeoutExpired: Command '['dot', '/var/folders/0y/m29sdh053119js5w5rtg58740000gn/T/graphvizer.dot', '-Tpng', '-o', '/var/folders/0y/m29sdh053119js5w5rtg58740000gn/T/graphvizer.png']' timed out after 3 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/***/Library/Application Support/Sublime Text 3/Packages/Graphvizer/graphvizer.py", line 73, in dot_thread
    except TimeoutExpired:
NameError: global name 'TimeoutExpired' is not defined
```

I guess changing `except TimeoutExpired:` to `except subprocess.TimeoutExpired:` will fix the issue

**Comment by hao-lee** [comment]
Hi, You are right. Thanks for your bug fix!

**Comment by hao-lee** [comment]
Done!
