### ISSUE TITLE
Unable to render images, Python and Permission errors?

### ISSUE THREAD

**Issue by S-P-A-C-E-B-A-R** [hao-lee/Graphvizer#23]
**Problem:**  Graphvizer does not render new images on edit, save, or build on a fresh installation.
**Sublime Console Output on Startup:**
```
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/../AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/../AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/../AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.098884
startup time: 0.143884
first paint time: 0.145884
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-enum
reloading plugin 0_package_control_loader.50-typing
reloading plugin Graphvizer.graphvizer
reloading plugin Graphvizer.syntaxchecker
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\..\AppData\Roaming\Sublime Text 3\Installed Packages\Graphvizer.sublime-package\graphvizer.py", line 112, in dot_thread
    cwd=self.get_cwd(view))
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
PermissionError: [WinError 5] Access is denied

Package Control: Skipping automatic upgrade, last run at 2020-09-30 14:01:13, next run at 2020-09-30 15:01:13 or after
```

### Procedure followed
**Versions**
Windows 10 x64 (1903)
Sublime V3.2.2 (3211)
Python3 V3.8.6
Graphviz V2.44.1 (20200629.0800)

**Process**
0. A recent copy of Python3 and GraphViz are installed and were previously added to my system path.
1. I installed Graphvizer on a fresh installation of Sublime via the Package Manager.
2. I opened the settings config via Preferences -> Package Settings -> Graphizer -> Settings.
3. Added dot path and changed display setting (see attachments).
**Graphvizer:sublime-settings -- User**
> // Settings in here override those in the left side
> 
> {
> 	"dot_cmd_path": "C:\\Program Files (x86)\\GraphViz\\bin",
> 	"show_image_with": "tab",
> }
> 
4. Began a new file, set the syntax to "Graphviz (DOT)" via View -> Syntax.
5. Created a new file, Edited, Saved, Deleted, and repeat for the following code:
**example.dot**
```
digraph example {
	node1 [
		shape=record,
		label="<f0> test"
	];
	node1:f0->a;
	a->b->c;
	b->e;
}
```
5. Manually generated the image from command prompt.
![image](https://user-images.githubusercontent.com/72162631/94730275-fb0a4580-0330-11eb-93fd-fd4df7bab158.png)
6. Edited, saved, example.dot. No render occurred.
7. Ran sublime with and without administrative permissions (steps 3-6).
![image](https://user-images.githubusercontent.com/72162631/94728534-656db680-032e-11eb-91ab-ce1b1e6656d8.png)

**Comment by S-P-A-C-E-B-A-R** [comment]
The path points beyond the binary (bin) directory and directly to the executable. This applies to all operating systems. This is already documented in the manual - I just failed to complete that step.

**Graphvizer:sublime-settings -- User**
> "dot_cmd_path": "C:\\Program Files (x86)\\GraphViz\\bin\\dot.exe",

**Comment by hao-lee** [comment]
Sorry for the delay. I'm on vacation :smirk: . Glad to see you have addressed this problem.
